### ISSUE TITLE
Don't modify 'Switch Windows` behavior

### ISSUE THREAD

**Issue by smichel17** [dsboger/gnome-shell-extension-super-tab-launcher#4]
**Preface:** *I often quickly tap and release alt-tab to swap between windows. When there's only a single window open, this automatically starts the first favorite, which I then need to close (more work compared to hitting alt-tab again, if there were two windows open). This is not a big deal, since I almost always have more than one window open; this addon is very useful (thank you!) -- worth the minor annoyance.*

**Actual issue:** 'Switch Windows' is a shortcut that is not mapped by default (at least in Fedora); I've mapped it to `ctrl-enter`. It's similar to 'Switch Applications' (`alt-tab`/`super-tab`), except that (1) it does not group windows of the same application, and (2) *it only shows windows on the current workspace.*

When I have 2 windows open on a workspace, I often use `ctrl-enter` to quickly jump between them. It's also fairly common for me to have only a single window on a workspace. Thus, I hit the issue mentioned in the preface far more often.

There's another sometimes-undesirable interaction between 'Switch Windows' and this addon: I have gnome-terminal in my favorites. If I have a terminal open on workspace 1, and then I move to workspace 2, selecting the terminal entry via `ctrl-tab` will launch a new terminal on the current workspace, rather than switching to workspace 1 and focusing the existing terminal.

---

I see from #1 that it may not be possible to choose which switching shortcuts are affected by this extension. I'm hoping that this is different because it uses a different shortcut (as opposed to, I think `alt-tab` and `super-tab` are two different key combinations for the same shortcut, `Switch Applications`). However, if it is the same issue, maybe it would be easier to switch to favorites on other workspaces instead of launching a new window?

**Comment by dsboger** [comment]
I've modified the Switch Windows action in order to fix #3, but I foresaw that someone would want to disable or make that optional. I'll split the two modifications in two different extensions, so you can enable only the extension that is of interest.

With respect to windows on different workspaces, the extension tries to respect the hidden settings `org.gnome.shell.app-switcher current-workspace-only` (for Switch Application, defaults to `false`) and `org.gnome.shell.window-switcher current-workspace-only` (for Switch Window, defaults to `true`). But some applications define their own behavior for the "new window" action, so that is hard to perfect.

**Comment by dsboger** [comment]
I've splitted the extensions. This one goes back to only modifying Switch Applications. The Switch Windows action is now modified by https://github.com/dsboger/gnome-shell-extension-window-switcher-launcher.

**Comment by smichel17** [comment]
Thank you, and again for the quick response :)
